[server]
port = 8080

[databases]
[databases.starknetid]
name = "starknetid"
connection_string = "xxxxxx"
[databases.sales]
name = "sepolia"
connection_string = "xxxxxx"
[databases.free_domains]
name = "sepolia_free_domains"
connection_string = "xxxxxx"

[watchtower]
endpoint = "https://api.watchtower.starknet.id/service/add_message"
app_id = "XXXXXXXXXXXXXXXXX"
token = "XXXXXXXXXXXXXXXXX"
enabled = true
[watchtower.types]
info = "goerli/info"
warning = "goerli/warning"
severe = "goerli/severe"

[contracts]
starknetid = "0xXXXXXXXXXXXX"
naming = "0xXXXXXXXXXXXX"
verifier = "0xXXXXXXXXXXXX"
old_verifier = "0xXXXXXXXXXXXX"
pop_verifier = "0xXXXXXXXXXXXX"
pp_verifier = "0xXXXXXXXXXXXX"
argent_multicall = "0xXXXXXXXXXXXX"
free_domains = "0xXXXXXXXXXXXX"

[paymaster]
api_key = "xxxxxx"
api_url = "https://starknet.api.avnu.fi/paymaster/v1" # https://sepolia.api.avnu.fi/paymaster/v1 on testnet

[variables]
rpc_url = "xxxxxx"
refresh_delay = 60                                  # in seconds
ipfs_gateway = "https://gateway.pinata.cloud/ipfs/" # or https://ipfs.io/ipfs/
discord_token = "xxxxxx"
discord_api_url = "https://discord.com/api"
twitter_api_key = "xxxxxx"
twitter_api_url = "xxxxxx"
github_api_url = "https://api.github.com"

[starkscan]
api_url = "https://api-testnet.starkscan.co/api/v0"
api_key = "xxxxxx"

[custom_resolvers]
"0xXXXXXXXXXXXX" = ["domain.stark"]

[solana]
rpc_url = "https://xxxxxxx.solana-mainnet.quiknode.pro/xxxxxxx"
private_key = "xxxxxxx"

[altcoins]
avnu_api = "https://starknet.impulse.avnu.fi/v1"
private_key = "123"

# Ethereum (ETH) is not enabled for the moment as it is already supported by default buy.
# [altcoins.ETH]
# address = "0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"
# min_price = 1
# max_price = 1
# decimals = 18
# max_quote_validity = 3600 # in seconds for ETH

[altcoins.STRK]
address = "0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d"
min_price = 500
max_price = 5000
decimals = 18
max_quote_validity = 300                                                                   # it moves faster so we reduce the quote validity
auto_renew_contract = "0x078F63fcD145Ddc6ca932E562b466AFbfD7c9E882C9aa70f3e5b2ce05cD892eA"

[altcoins.USDC]
address = "0x053c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8"
min_price = 2000
max_price = 10000
decimals = 6                                                                   # not sure really
max_quote_validity = 600

[altcoins.USDT]
address = "0x068f5c6a61780768455de69077e07e89787839bf8166decfbf92b645209c0fb8"
min_price = 2000
max_price = 10000
decimals = 18
max_quote_validity = 600

[offchain_resolvers]

[offchain_resolvers.NOTION]
root_domain = "notion.stark"
resolver_address = "0x153be68cf8fc71138610811dd2b4fa481eb99f3eedcb3fce7369569055be275"
uri = ["https://sepolia.api.ccip-demo.starknet.id/resolve?domain="]

[evm]
private_key = "0xXXXXXXXXXXXX"

[evm_networks]
polygon = 2147483785
optimism = 2147483658
base = 2147492101
arbitrum = 2147525809

[evm_records_verifiers]

[evm_records_verifiers."com.discord"]
verifier_contracts = [
    "0x0182EcE8173C216A395f4828e1523541b7e3600bf190CB252E1a1A0cE219d184",
]
field = "discord"
handler = "GetDiscordName"

[evm_records_verifiers."com.github"]
verifier_contracts = [
    "0x0182EcE8173C216A395f4828e1523541b7e3600bf190CB252E1a1A0cE219d184",
]
field = "github"
handler = "GetGithubName"

[evm_records_verifiers."com.twitter"]
verifier_contracts = [
    "0x0182EcE8173C216A395f4828e1523541b7e3600bf190CB252E1a1A0cE219d184",
]
field = "twitter"
handler = "GetTwitterName"

[free_domains]
priv_key = "0xXXXXXXXXXXXX"
